### ISSUE TITLE
CSS Broken

### ISSUE THREAD

**Issue by CepheiA2** [mordachai/household-csb#2]
Foundry V11 build 309
Chrome

Character Sheet, Css is kinda broken, can you fix it?
![image](https://github.com/mordachai/household-csb/assets/85868381/485c5fe0-010f-4e6e-9645-c26096bec30b)

**Comment by mordachai** [comment]
its not broken, its like this only on the template. Create a character and assign it the Player Template and see how it is

**Comment by CepheiA2** [comment]
Oh, Thank you for the work you're making!
and Thank you for the answer i appreciate it
